FROM nginx:stable-alpine

#RUN adduser -D -H -u 1000 -s /bin/bash www-data -G www-data
# ensure www-data user exists
RUN set -x ; \
  addgroup -g 82 -S www-data ; \
  adduser -u 82 -D -S -G www-data www-data && exit 0 ; exit 1

COPY conf/ /etc/nginx/
COPY logs/ /etc/nginx/logs

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

