FROM php:8.4-fpm-alpine

ENV HOME /www-data
USER root

RUN apk update
RUN apk add --no-cache \
    $PHPIZE_DEPS \
    openssl-dev 

RUN  apk add git libzip-dev zip grep  libpng-dev nodejs yarn icu-dev



RUN docker-php-source extract \
    && docker-php-ext-install pdo_mysql  gd zip intl\
    && docker-php-source delete
RUN pecl channel-update pecl.php.net


RUN pecl install redis \
    && pecl install \
    && docker-php-ext-enable redis \
    && docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# COPY config/php.ini  /usr/local/etc/php/php.ini

RUN pecl install mongodb \
    && docker-php-ext-enable mongodb
    # &&  echo "extension=mongo.so" > $PHP_INI_DIR/conf.d/mongo.ini

RUN apk add php84-pecl-imagick-dev --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community
RUN apk --update add imagemagick imagemagick-dev
RUN pecl install imagick
RUN docker-php-ext-enable imagick

#add php user
#RUN useradd -ms /bin/bash php
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN chown -R www-data /www-data/.composer
RUN mkdir /www-data/.vscode-server
RUN chown -R www-data /www-data/.vscode-server
USER www-data
WORKDIR /var/www
EXPOSE 9003
EXPOSE 9000

